# -*- coding: utf-8 -*-
"""pathPlot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13P2r5i8i2IPMnlzlCVXZTkZVAJlxpoOR
"""

# A
# {(0, 10): 1.0, (1, 18): 1.0, (2, 19): 1.0, (3, 2): 1.0, (3, 17): 1.0, (4, 3): 1.0, (6, 9): 1.0, (7, 6): 1.0, (8, 13): 1.0,
#  (9, 20): 1.0, (10, 14): 1.0, (11, 0): 1.0, (13, 3): 1.0, (14, 15): 1.0, (15, 16): 1.0, (16, 1): 1.0, (17, 4): 1.0, (18, 8): 1.0, (19, 7): 1.0, (20, 11): 1.0}


seq_bc_20A = [0,10,14,15,16,1,18,8,13,3,17,4,3,2,19,7,6,9,20,11,0]
seq_rl_20A =[0, 20, 1, 18, 15, 10, 12, 10, 20, 9, 8, 7, 12, 11, 6, 12, 10, 15, 10, 16, 13, 11, 7, 6, 10, 12, 7, 9, 6, 11, 20, 7, 20, 6, 14, 12, 2, 3, 4, 9, 2, 13, 15, 19, 1, 4, 19, 17, 16, 2, 5, 16, 0]
seq_tb_20A =[0, 20, 12, 9, 10, 14, 5, 15, 16, 1, 18, 8, 11, 9, 6, 7, 11, 19, 2, 17, 4, 3, 2, 13, 0]

X= {0: 0, 1: 316, 2: -434, 3: -299, 4: -403, 5: 415, 6: -380, 7: -414, 8: 46, 9: -269, 10: 140, 11: -335, 12: -219, 13: -188, 14: 353, 15: 396, 16: 464, 17: -403, 18: 171, 19: -441, 20: -202}
Y= {0: 0, 1: 275, 2: 164, 3: 365, 4: 500, 5: -30, 6: -348, 7: -268, 8: 143, 9: -193, 10: -40, 11: -83, 12: -284, 13: 262, 14: 8, 15: 41, 16: 324, 17: 369, 18: 335, 19: 139, 20: -230}

# assert len(X) = len(Y)
XY=[]
for i in range(len(X)):
    XY.append((X[i],Y[i]))

XY

from matplotlib.patches import ConnectionPatch
import matplotlib.pyplot as plt

fig, ax = plt.subplots(1,1, figsize=(15, 15))

# Draw a simple arrow between two points in axes coordinates
# within a single axes.

select_seq = seq_rl_20A

for i in range(len(select_seq)-1):
    xyA = XY[select_seq[i]]
    xyB = XY[select_seq[i+1]]
    # print(xyA)
    coordsA = "data"
    coordsB = "data"
    con = ConnectionPatch(xyA, xyB, coordsA, coordsB,
                        arrowstyle="-|>", shrinkA=5, shrinkB=5,
                        mutation_scale=20, fc="w")
    ax.plot(xyA[0],xyA[1], "o")
    ax.plot(xyB[0],xyB[1], "o")
    ax.add_artist(con)
ax.plot(0, 0, "s")


ax.set_xlim(-550, 550)
ax.set_ylim(-550, 550)

plt.show()

"""# 20B"""

X= {0: 0, 1: 492, 2: 358, 3: -69, 4: -59, 5: 472, 6: 350, 7: 55, 8: -346, 9: -400, 10: 425, 11: -389, 12: 275, 13: 269, 14: 361, 15: 444, 16: 27, 17: 396, 18: -300, 19: -56, 20: 94}
Y= {0: 0, 1: 94, 2: 322, 3: 246, 4: -450, 5: -218, 6: 441, 7: 274, 8: -302, 9: 64, 10: 257, 11: 292, 12: -119, 13: -118, 14: -336, 15: -268, 16: 351, 17: -257, 18: -450, 19: -346, 20: 281}
# assert len(X) = len(Y)
XY=[]
for i in range(len(X)):
    XY.append((X[i],Y[i]))

# B
# {(0, 3): 1.0, (1, 10): 1.0, (2, 20): 1.0, (3, 13): 1.0, (4, 19): 1.0, (6, 2): 1.0, (7, 16): 1.0, (8, 18): 1.0, (9, 8): 1.0, (10, 6): 1.0, 
# (11, 9): 1.0, (12, 13): 1.0, (13, 12): 1.0, (13, 14): 1.0, (14, 15): 1.0, (15, 17): 1.0, (16, 11): 1.0, (17, 1): 1.0, (18, 4): 1.0, (19, 0): 1.0, (20, 7): 1.0}

#
seq_bc_20B = [0,3,13,12,13,14,15,17,1,10,6,2,20,7,16,11,9,8,18,4,19,0]
seq_rl_20B =[ 0, 11, 14,  6,  8, 12,  6, 16, 19,  2,  3,  4, 5, 15, 19, 12, 16,  2,  4, 19, 13, 15, 10, 15,  6, 18, 13,  7, 19,  2,  9,  1, 20, 19, 16, 17, 20, 13, 15,  2, 16, 17,  8,  0]
seq_tb_20B =[ 0,11,9,8,18,4,3 ,2 ,6,16,7,20,10,1,13,12,17,5,15,14, 4, 19, 0]

from matplotlib.patches import ConnectionPatch
import matplotlib.pyplot as plt

fig, ax = plt.subplots(1,1, figsize=(15, 15))

# Draw a simple arrow between two points in axes coordinates
# within a single axes.

select_seq = seq_tb_20B

for i in range(len(select_seq)-1):
    xyA = XY[select_seq[i]]
    xyB = XY[select_seq[i+1]]
    # print(xyA)
    coordsA = "data"
    coordsB = "data"
    con = ConnectionPatch(xyA, xyB, coordsA, coordsB,
                        arrowstyle="-|>", shrinkA=5, shrinkB=5,
                        mutation_scale=20, fc="w")
    ax.plot(xyA[0],xyA[1], "o")
    ax.plot(xyB[0],xyB[1], "o")
    ax.add_artist(con)
ax.plot(0, 0, "s")


ax.set_xlim(-550, 550)
ax.set_ylim(-550, 550)

plt.show()

"""# 20C"""

X={0: 0, 1: 8, 2: -144, 3: 138, 4: -291, 5: -124, 6: -16, 7: -439, 8: 10, 9: 261, 10: -206, 11: 58, 12: 428, 13: 224, 14: -278, 15: -378, 16: -414, 17: 488, 18: -157, 19: 365, 20: 190}
Y={0: 0, 1: 177, 2: 56, 3: -346, 4: 428, 5: 148, 6: 94, 7: 401, 8: 486, 9: -419, 10: 11, 11: -337, 12: 328, 13: 230, 14: -54, 15: -390, 16: 297, 17: 497, 18: -240, 19: -100, 20: 272}
XY=[]
for i in range(len(X)):
    XY.append((X[i],Y[i]))

dict ={(0, 6): 1.0, (1, 5): 1.0, (1, 8): 2.0, (1, 13): 1.0, (1, 19): 1.0, (2, 5): 1.0, (2, 6): 1.0, (3, 9): 1.0, (3, 11): 1.0, (4, 7): 1.0, (5, 1): 2.0, (5, 2): 1.0, (6, 0): 1.0, (6, 1): 1.0, \
 (7, 16): 1.0, (8, 4): 1.0, (8, 17): 1.0, (9, 3): 1.0, (10, 5): 1.0, (11, 3): 1.0, (11, 18): 1.0, (12, 13): 1.0, (13, 20): 2.0, (14, 10): 1.0, (15, 14): 1.0, (16, 2): 1.0, (17, 20): 1.0, \
 (18, 15): 1.0, (19, 11): 1.0, (20, 1): 2.0, (20, 12): 1.0}

arc_list= []
for idx,val in dict.items():
    arc_list.append(idx)

# 
# seq_bc_20C = [0,6,1,5,1,8,4,7,16,2,5,2,6,0] [11,18,15,14,10,5,1,8,17,20,1,13,20,1,19,11,3,9,3] 
seq_rl_20C =[ 0, 19, 13, 10,  5, 15, 11,  2, 11,  8,  9, 18, 9,  5, 1,  5, 16, 18, 11,  1, 10, 17, 7, 6, 5, 13, 14,  8, 12, 14,  2, 13, 20,7, 2, 3, 14, 10, 5,4, 1, 8,19,  9, 15, 13, 10, 13,  0]
seq_tb_20C = [ 0, 19, 13,  6, 13, 20, 17, 12, 1, 5, 8 ,4,7, 16, 10,  2, 5, 18,  9, 11, 3, 18, 15,14, 0]

"""# Plot from sequence"""

from matplotlib.patches import ConnectionPatch
import matplotlib.pyplot as plt

fig, ax = plt.subplots(1,1, figsize=(15, 15))

# Draw a simple arrow between two points in axes coordinates
# within a single axes.

select_seq = seq_tb_20C

for i in range(len(select_seq)-1):
    xyA = XY[select_seq[i]]
    xyB = XY[select_seq[i+1]]
    # print(xyA)
    coordsA = "data"
    coordsB = "data"
    con = ConnectionPatch(xyA, xyB, coordsA, coordsB,
                        arrowstyle="-|>", shrinkA=5, shrinkB=5,
                        mutation_scale=20, fc="w")
    ax.plot(xyA[0],xyA[1], "o")
    ax.plot(xyB[0],xyB[1], "o")
    ax.add_artist(con)
ax.plot(0, 0, "s")


ax.set_xlim(-550, 550)
ax.set_ylim(-550, 550)

plt.show()

"""# Plot from arcs list"""

from matplotlib.patches import ConnectionPatch
import matplotlib.pyplot as plt

fig, ax = plt.subplots(1,1, figsize=(15, 15))

# Draw a simple arrow between two points in axes coordinates
# within a single axes.

# select_seq = seq_tb_20B

for (i,j) in arc_list:
    xyA = XY[i]
    xyB = XY[j]
    # print(xyA)
    coordsA = "data"
    coordsB = "data"
    con = ConnectionPatch(xyA, xyB, coordsA, coordsB,
                        arrowstyle="-|>", shrinkA=5, shrinkB=5,
                        mutation_scale=20, fc="w")
    ax.plot(xyA[0],xyA[1], "o")
    ax.plot(xyB[0],xyB[1], "o")
    ax.add_artist(con)
ax.plot(0, 0, "s")


ax.set_xlim(-550, 550)
ax.set_ylim(-550, 550)

plt.show()

"""# 40A"""

X={0: 0, 1: -139, 2: -447, 3: 218, 4: 440, 5: 104, 6: 426, 7: 332, 8: -122, 9: 306, 10: -256, 11: 452, 12: 432, 13: -178, 14: 440, 15: 377, 16: -176, 17: 47, 18: -67, 19: -424, 20: -442, 21: -341, 22: 31, 23: -487, 24: 95, 25: 237, 26: -69, 27: -191, 28: -2, 29: -117, 30: -165, 31: -356, 32: -293, 33: 156, 34: 188, 35: -61, 36: -424, 37: -3, 38: -489, 39: 241, 40: -159}
Y={0: 0, 1: 25, 2: 20, 3: -116, 4: -351, 5: 136, 6: -50, 7: 54, 8: 12, 9: 97, 10: 318, 11: -297, 12: 85, 13: -79, 14: 169, 15: 432, 16: 38, 17: 60, 18: -114, 19: 9, 20: 180, 21: -219, 22: -150, 23: -352, 24: -364, 25: 328, 26: 384, 27: -387, 28: -432, 29: -405, 30: 450, 31: -118, 32: 147, 33: -190, 34: 474, 35: -485, 36: -459, 37: -355, 38: -310, 39: 446, 40: 491}
XY=[]
for i in range(len(X)):
    XY.append((X[i],Y[i]))

dict ={(0, 17): 1.0, (1, 8): 1.0, (1, 13): 1.0, (1, 16): 1.0, (2, 10): 1.0, (2, 19): 6.0, (3, 6): 1.0, (3, 22): 1.0, (5, 1): 1.0, (5, 3): 1.0, (6, 7): 1.0, (6, 12): 1.0, (7, 3): 1.0, (8, 0): 1.0, \
       (9, 5): 1.0, (10, 19): 1.0, (10, 30): 1.0, (12, 6): 1.0, (12, 9): 1.0, (13, 21): 3.0, (14, 12): 1.0, (15, 14): 1.0, (15, 25): 1.0, (16, 1): 2.0, (17, 5): 1.0, (18, 13): 2.0, (19, 2): 6.0, \
       (19, 10): 1.0, (20, 2): 1.0, (21, 31): 1.0, (21, 32): 1.0, (21, 38): 1.0, (22, 18): 2.0, (23, 36): 1.0, (24, 28): 1.0, (24, 33): 1.0, (25, 39): 1.0, (26, 34): 1.0, (27, 29): 1.0, (27, 35): 1.0, \
       (28, 24): 1.0, (28, 37): 1.0, (29, 27): 1.0, (30, 26): 1.0, (30, 40): 1.0, (31, 16): 1.0, (32, 20): 1.0, (33, 24): 1.0, (34, 39): 1.0, (35, 28): 1.0, (36, 27): 1.0, (37, 22): 1.0, (38, 23): 1.0, \
       (39, 15): 2.0, (40, 30): 1.0}

arc_list= []
for idx,val in dict.items():
    arc_list.append(idx)

# 
# seq_bc_40A = [0,6,1,5,1,8,4,7,16,2,5,2,6,0] [11,18,15,14,10,5,1,8,17,20,1,13,20,1,19,11,3,9,3] 
seq_rl_40A ='[ 0 5 6  7 29  8 12 25 24 36 28  8 19 20 28  5 32 27 19  1 25  2  2 25 \
  29 20  8 28 15 13 30  1 20 21 35 29 17  4 16  9 13  2 40 38 15 24 32  6 \
  34 11 19 23  3 28  9  2 35 31 38  1  8 28 30  5 35 17  8 26 36  7 26 40 \
  39 18 34 34 19 13 32 34 20 18 29 30 22  5 25 28 17 17 14 33 37  9 12 16 \
   6 24 12 38 14  8 29 10 35 27 40 26 16 32 17 17 35  6  5 22 16  8 15 29 \
   4  0 ]'
seq_tb_40A = '[ 0 18 17 17 31 21 38 38 23 36 36 36 36 27 22 5 9 6 6 3 33 11 4 \
 28 35 29 37 37 37 24 6 7 12 12 12 14 14 25 15 15 15 39 39 34 26 \
 26 26 30 30 40 40 40 40 19 19 19 19 10 2 20 32 32 32 16 1 1 8 8 8 8 13 0 ]'

# print(seq_rl_40A.split(" ")[1:-1])
seq_rl_40A_split= seq_rl_40A.split(" ")[1:-1]
seq_rl_40A_split= [int(i) for i in seq_rl_40A_split if i !=""]
print(seq_rl_40A_split)
seq_rl_40A_noconseq= [seq_rl_40A_split[i] for i in range(len(seq_rl_40A_split)-1) if seq_rl_40A_split[i]!=seq_rl_40A_split[i+1]]
seq_rl_40A_noconseq.append(seq_rl_40A_split[-1])
print(seq_rl_40A_noconseq)

# print(seq_rl_40A.split(" ")[1:-1])
seq_tb_40A_split= seq_tb_40A.split(" ")[1:-1]
seq_tb_40A_split= [int(i) for i in seq_tb_40A_split if i !=""]
print(seq_tb_40A_split)
seq_tb_40A_noconseq= [seq_tb_40A_split[i] for i in range(len(seq_tb_40A_split)-1) if seq_tb_40A_split[i]!=seq_tb_40A_split[i+1]]
seq_tb_40A_noconseq.append(seq_tb_40A_split[-1])
print(seq_tb_40A_noconseq)

from matplotlib.patches import ConnectionPatch
import matplotlib.pyplot as plt

fig, ax = plt.subplots(1,1, figsize=(15, 15))

# Draw a simple arrow between two points in axes coordinates
# within a single axes.

# select_seq = seq_tb_20B

for (i,j) in arc_list:
    xyA = XY[i]
    xyB = XY[j]
    # print(xyA)
    coordsA = "data"
    coordsB = "data"
    con = ConnectionPatch(xyA, xyB, coordsA, coordsB,
                        arrowstyle="-|>", shrinkA=5, shrinkB=5,
                        mutation_scale=20, fc="w")
    ax.plot(xyA[0],xyA[1], "o")
    ax.plot(xyB[0],xyB[1], "o")
    ax.add_artist(con)
ax.plot(0, 0, "s")


ax.set_xlim(-550, 550)
ax.set_ylim(-550, 550)

plt.show()

from matplotlib.patches import ConnectionPatch
import matplotlib.pyplot as plt

fig, ax = plt.subplots(1,1, figsize=(15, 15))

# Draw a simple arrow between two points in axes coordinates
# within a single axes.

select_seq = seq_tb_40A_noconseq

for i in range(len(select_seq)-1):
    xyA = XY[select_seq[i]]
    xyB = XY[select_seq[i+1]]
    # print(xyA)
    coordsA = "data"
    coordsB = "data"
    con = ConnectionPatch(xyA, xyB, coordsA, coordsB,
                        arrowstyle="-|>", shrinkA=5, shrinkB=5,
                        mutation_scale=20, fc="w")
    ax.plot(xyA[0],xyA[1], "o")
    ax.plot(xyB[0],xyB[1], "o")
    ax.add_artist(con)
ax.plot(0, 0, "s")


ax.set_xlim(-550, 550)
ax.set_ylim(-550, 550)

plt.show()

"""# 40B"""

X={0: 0, 1: 126, 2: 261, 3: -8, 4: -262, 5: -383, 6: -147, 7: 21, 8: 123, 9: -426, 10: -277, 11: -115, 12: -248, 13: 487, 14: 95, 15: -112, 16: 51, 17: 75, 18: 498, 19: -45, 20: -51, 21: -221, 22: -35, 23: 494, 24: -35, 25: -279, 26: -263, 27: -402, 28: 459, 29: -55, 30: 377, 31: -82, 32: 457, 33: 413, 34: -476, 35: -387, 36: 391, 37: 187, 38: -396, 39: 368, 40: 200}
Y={0: 0, 1: -201, 2: -16, 3: 149, 4: -411, 5: 19, 6: 345, 7: 271, 8: -140, 9: 272, 10: 54, 11: 69, 12: 15, 13: -338, 14: 168, 15: 21, 16: -321, 17: -229, 18: 477, 19: 296, 20: -185, 21: 467, 22: -201, 23: 283, 24: -81, 25: 153, 26: 171, 27: -14, 28: -258, 29: 440, 30: -46, 31: 214, 32: 368, 33: 199, 34: -155, 35: 173, 36: -256, 37: 320, 38: -149, 39: -139, 40: -477}
XY=[]
for i in range(len(X)):
    XY.append((X[i],Y[i]))

dict ={(0, 24): 1.0, (1, 8): 2.0, (1, 17): 1.0, (2, 30): 1.0, (3, 7): 1.0, (3, 14): 2.0, (4, 38): 1.0, (5, 25): 2.0, (6, 11): 1.0, (6, 21): 1.0, (7, 19): 2.0, (8, 0): 1.0, 
       (8, 1): 1.0, (9, 35): 1.0, (10, 12): 3.0, (11, 6): 1.0, (12, 10): 2.0, (12, 15): 1.0, (13, 28): 1.0, (14, 3): 1.0, (14, 37): 1.0, (15, 31): 1.0, (16, 4): 1.0, (16, 40): 1.0, 
       (17, 1): 1.0, (17, 16): 1.0, (18, 32): 1.0, (19, 3): 1.0, (19, 6): 1.0, (20, 22): 1.0, (21, 29): 1.0, (22, 17): 1.0, (23, 33): 1.0, (24, 20): 1.0, (25, 9): 1.0, (25, 10): 1.0, 
       (25, 26): 1.0, (26, 25): 1.0, (27, 5): 1.0, (28, 13): 1.0, (28, 36): 1.0, (29, 7): 1.0, (30, 39): 1.0, (31, 3): 1.0, (32, 18): 1.0, (32, 23): 1.0, (33, 2): 1.0, (34, 27): 1.0, 
       (35, 5): 1.0, (36, 1): 1.0, (36, 28): 1.0, (37, 32): 1.0, (38, 34): 1.0, (39, 36): 1.0, (40, 16): 1.0}

arc_list= []
for idx,val in dict.items():
    arc_list.append(idx)

# 
# seq_bc_40A = [0,6,1,5,1,8,4,7,16,2,5,2,6,0] [11,18,15,14,10,5,1,8,17,20,1,13,20,1,19,11,3,9,3] 
seq_rl_40B ='[ 0  2 40 13 34 12 27  9  3 14 27  1 15 20 19  5  7 15 14 19 13  3 27 10 \
  12 37 17 26  8 38  8 27 17 10 18  6 32  7 23 21 11  7 17 12 14 39 33 14 \
  25 21 22 29 30 20 30 29 10 33 22  5 33 34 24  6  3 15 23 38 36  2  9 30 \
   2 11 39 16  7 32 26 28 14 31 16 31 35 40 14  3 11 17 19 35 23 30 30 10 \
  36  6 20  4 22 32 33 12 33 23  4 13 39 16 16 16 10 13 19 39 28 27 29  7 \
  39  0 ]'
seq_tb_40B = '[ 0  2  2 30 30 30 30 30 39 39 39 39 39 28 13 13 13 28 36 36 40  4 20 20 \
 22 22 17 17 24  8  8 17 16 16 16 16 17  1 15 15 15 11  7 19  3  3 19 29 \
 29 21 21 10 10 10 26 25 12 10 27 27 27 27  9 35 35  5 27 34 34 38 10 11 \
 11 31 31 19  6 19  7  7 37 23 23 32 32 18 23 33 33 33 33  2 14 14 14 14 \
 14  7  7  3  0 ]'

# print(seq_rl_40A.split(" ")[1:-1])
seq_rl_40B_split= seq_rl_40B.split(" ")[1:-1]
seq_rl_40B_split= [int(i) for i in seq_rl_40B_split if i !=""]
print(seq_rl_40B_split)
seq_rl_40B_noconseq= [seq_rl_40B_split[i] for i in range(len(seq_rl_40B_split)-1) if seq_rl_40B_split[i]!=seq_rl_40B_split[i+1]]
seq_rl_40B_noconseq.append(seq_rl_40B_split[-1])
print(seq_rl_40B_noconseq)

# print(seq_rl_40A.split(" ")[1:-1])
seq_tb_40B_split= seq_tb_40B.split(" ")[1:-1]
seq_tb_40B_split= [int(i) for i in seq_tb_40B_split if i !=""]
print(seq_tb_40B_split)
seq_tb_40B_noconseq= [seq_tb_40B_split[i] for i in range(len(seq_tb_40B_split)-1) if seq_tb_40B_split[i]!=seq_tb_40B_split[i+1]]
seq_tb_40B_noconseq.append(seq_tb_40B_split[-1])
print(seq_tb_40B_noconseq)

from matplotlib.patches import ConnectionPatch
import matplotlib.pyplot as plt

fig, ax = plt.subplots(1,1, figsize=(15, 15))

# Draw a simple arrow between two points in axes coordinates
# within a single axes.

# select_seq = seq_tb_20B

for (i,j) in arc_list:
    xyA = XY[i]
    xyB = XY[j]
    # print(xyA)
    coordsA = "data"
    coordsB = "data"
    con = ConnectionPatch(xyA, xyB, coordsA, coordsB,
                        arrowstyle="-|>", shrinkA=5, shrinkB=5,
                        mutation_scale=20, fc="w")
    ax.plot(xyA[0],xyA[1], "o")
    ax.plot(xyB[0],xyB[1], "o")
    ax.add_artist(con)
ax.plot(0, 0, "s")


ax.set_xlim(-550, 550)
ax.set_ylim(-550, 550)

plt.show()

from matplotlib.patches import ConnectionPatch
import matplotlib.pyplot as plt

fig, ax = plt.subplots(1,1, figsize=(15, 15))

# Draw a simple arrow between two points in axes coordinates
# within a single axes.

select_seq = seq_rl_40B_noconseq

for i in range(len(select_seq)-1):
    xyA = XY[select_seq[i]]
    xyB = XY[select_seq[i+1]]
    # print(xyA)
    coordsA = "data"
    coordsB = "data"
    con = ConnectionPatch(xyA, xyB, coordsA, coordsB,
                        arrowstyle="-|>", shrinkA=5, shrinkB=5,
                        mutation_scale=20, fc="w")
    ax.plot(xyA[0],xyA[1], "o")
    ax.plot(xyB[0],xyB[1], "o")
    ax.add_artist(con)
ax.plot(0, 0, "s")


ax.set_xlim(-550, 550)
ax.set_ylim(-550, 550)

plt.show()

"""# 40C"""

X={0: 0, 1: 428, 2: -29, 3: 248, 4: 139, 5: -203, 6: 75, 7: 130, 8: -393, 9: -249, 10: 238, 11: -204, 12: 35, 13: 499, 14: 195, 15: -200, 16: 310, 17: -151, 18: -227, 19: 134, 20: 213, 21: -325, 22: 53, 23: 155, 24: 406, 25: 167, 26: 122, 27: 266, 28: -303, 29: 454, 30: 339, 31: 81, 32: 312, 33: -333, 34: 478, 35: 424, 36: -259, 37: -52, 38: 489, 39: -318, 40: 378}
Y={0: 0, 1: -138, 2: 70, 3: 275, 4: -70, 5: 455, 6: 319, 7: -409, 8: 97, 9: -5, 10: 56, 11: -200, 12: -124, 13: -430, 14: -227, 15: 380, 16: -338, 17: -182, 18: -272, 19: 272, 20: -280, 21: 367, 22: 124, 23: -121, 24: 222, 25: 480, 26: -399, 27: -104, 28: -430, 29: 236, 30: -329, 31: -195, 32: -57, 33: 329, 34: 125, 35: 10, 36: 45, 37: -106, 38: 120, 39: 154, 40: -424}
XY=[]
for i in range(len(X)):
    XY.append((X[i],Y[i]))

dict ={(0, 2): 1.0, (1, 13): 1.0, (1, 35): 1.0, (2, 0): 1.0, (2, 15): 1.0, (2, 22): 1.0, (3, 6): 1.0, (3, 10): 1.0, (3, 24): 1.0, (3, 25): 1.0, (4, 27): 2.0, (5, 15): 5.0, (5, 21): 1.0, (6, 2): 1.0, (6, 19): 1.0, 
       (6, 25): 1.0, (7, 16): 1.0, (7, 26): 1.0, (8, 36): 1.0, (8, 39): 1.0, (9, 11): 1.0, (9, 36): 1.0, (10, 4): 1.0, (11, 17): 1.0, (11, 18): 1.0, (12, 23): 1.0, (12, 37): 1.0, (13, 40): 1.0, (14, 20): 1.0, (15, 2): 1.0, 
       (15, 5): 5.0, (16, 20): 1.0, (16, 30): 1.0, (17, 37): 1.0, (18, 11): 1.0, (18, 28): 1.0, (19, 3): 1.0, (19, 6): 1.0, (20, 7): 1.0, (20, 31): 1.0, (21, 33): 1.0, (22, 6): 1.0, (23, 4): 1.0, (24, 3): 1.0, (25, 3): 1.0, 
       (25, 19): 1.0, (26, 7): 1.0, (27, 32): 2.0, (28, 18): 1.0, (29, 3): 1.0, (30, 1): 1.0, 
       (31, 12): 1.0, (32, 1): 1.0, (32, 14): 1.0, (33, 8): 1.0, (34, 38): 1.0, (35, 34): 1.0, (36, 9): 1.0, (36, 39): 1.0, (37, 9): 1.0, (37, 12): 1.0, (38, 29): 1.0, (39, 5): 1.0, (39, 8): 1.0, (40, 16): 1.0}

arc_list= []
for idx,val in dict.items():
    arc_list.append(idx)

# 
# seq_bc_40A = [0,6,1,5,1,8,4,7,16,2,5,2,6,0] [11,18,15,14,10,5,1,8,17,20,1,13,20,1,19,11,3,9,3] 
seq_rl_40C ='[ 0 16 18 20 36 14 13 24 35 26 14 24 17 30  8 30 20 34 11 39 22 12 15  1 \
  37  2 31 11 34 16 33 16 29 21  1 37 32  6 37  5 33 34 24  8 38  8 16  6 \
  35 28 21 25 23 10  2  3 39 27 19 24 12 29 11 11 23  7 25 36 38 35  5 23 \
  32  2 13 36 21 23 34 22  9 40 18  8 30 17  5 10 39 15 32  7 21  7 39  3 \
  25 17 28  4 25  4 16 40 17 29 17  8 23  0]'
seq_tb_40C = '[ 0 16 16 16 16 40 13 1 1 35 10 19 3 3 25 25 25 24 24 24 24 34 34 29 34 38 35 35 32 32 32 30 30 30 14 23 23 27 23 23 4 4 12 37 37 37 17 17 17 28 28 11 11 11 39 39 39 39 5 5 15 5 22 6 2 36 21 33 8 8 8 8 9 22 2 31 7 7 26 20 18 17 17 23 0 ]'

# print(seq_rl_40A.split(" ")[1:-1])
seq_rl_40C_split= seq_rl_40C.split(" ")[1:-1]
seq_rl_40C_split= [int(i) for i in seq_rl_40C_split if i !=""]
print(seq_rl_40C_split)
seq_rl_40C_noconseq= [seq_rl_40C_split[i] for i in range(len(seq_rl_40C_split)-1) if seq_rl_40C_split[i]!=seq_rl_40C_split[i+1]]
seq_rl_40C_noconseq.append(seq_rl_40C_split[-1])
print(seq_rl_40C_noconseq)

# print(seq_rl_40A.split(" ")[1:-1])
seq_tb_40C_split= seq_tb_40C.split(" ")[1:-1]
seq_tb_40C_split= [int(i) for i in seq_tb_40C_split if i !=""]
print(seq_tb_40C_split)
seq_tb_40C_noconseq= [seq_tb_40C_split[i] for i in range(len(seq_tb_40C_split)-1) if seq_tb_40C_split[i]!=seq_tb_40C_split[i+1]]
seq_tb_40C_noconseq.append(seq_tb_40C_split[-1])
print(seq_tb_40C_noconseq)

from matplotlib.patches import ConnectionPatch
import matplotlib.pyplot as plt

fig, ax = plt.subplots(1,1, figsize=(15, 15))

# Draw a simple arrow between two points in axes coordinates
# within a single axes.

# select_seq = seq_tb_20B

for (i,j) in arc_list:
    xyA = XY[i]
    xyB = XY[j]
    # print(xyA)
    coordsA = "data"
    coordsB = "data"
    con = ConnectionPatch(xyA, xyB, coordsA, coordsB,
                        arrowstyle="-|>", shrinkA=5, shrinkB=5,
                        mutation_scale=20, fc="w")
    ax.plot(xyA[0],xyA[1], "o")
    ax.plot(xyB[0],xyB[1], "o")
    ax.add_artist(con)
ax.plot(0, 0, "s")


ax.set_xlim(-550, 550)
ax.set_ylim(-550, 550)

plt.show()

seq_tb_40C_noconseq

from matplotlib.patches import ConnectionPatch
import matplotlib.pyplot as plt

fig, ax = plt.subplots(1,1, figsize=(15, 15))

# Draw a simple arrow between two points in axes coordinates
# within a single axes.

select_seq = seq_rl_40C_noconseq

for i in range(len(select_seq)-1):
    xyA = XY[select_seq[i]]
    xyB = XY[select_seq[i+1]]
    # print(xyA)
    coordsA = "data"
    coordsB = "data"
    con = ConnectionPatch(xyA, xyB, coordsA, coordsB,
                        arrowstyle="-|>", shrinkA=5, shrinkB=5,
                        mutation_scale=20, fc="w")
    ax.plot(xyA[0],xyA[1], "o")
    ax.plot(xyB[0],xyB[1], "o")
    ax.add_artist(con)
ax.plot(0, 0, "s")


ax.set_xlim(-550, 550)
ax.set_ylim(-550, 550)

plt.show()